# Site settings
title: "Michael Lee"
email: "michaelsoolee@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Michael Lee is a craftsman of digital things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://michaelsoolee.com" # the base hostname & protocol for your site
twitter_username: michaelsoolee
github_username:  michaellee

# Build settings
markdown: redcarpet
permalink: /:title
paginate: 4
paginate_path: "/page/:num"
keep_files: [assets]

sass:
  style: :compressed

collections:
  notes:
    output: true
    permalink: /notes/:path
  links:
    output: true
    permalink: /:path

gems: [jekyll-paginate]
